DjangoTutorial/mysite/contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [

    path('', views.index, name='index'),

]

DjangoTutorial/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include(('polls.urls', 'polls'), namespace='polls')),
    path('contact/', include(('contact.urls', 'polls'), namespace='contact')),
]

DjangoTutorial/mysite/polls/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf.urls import include

urlpatterns = [

    path('', views.index, name='Index'),

    path('contact/', include(('contact.urls', 'contact'), namespace='contact')),

    path('<question_id>', views.detail, name='detail'),

    path('', views.index, name="index"),

    url('(?P<question_id>[0-9]+)/detail$', views.detail, name="detail"),

    url('(?P<question_id>[0-9]+)/results$', views.results, name="results"),

    url('(?P<question_id>[0-9]+)/vote$', views.vote, name="vote"),

]

DjangoTutorial/mysite/contact/models.py
from django.db import models

# Create your models here.

DjangoTutorial/mysite/polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):

    question_text = models.CharField(max_length=200)

    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):

    choice_text = models.CharField(max_length=200)

    num_of_votes = models.IntegerField(default=0)

    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

DjangoTutorial/mysite/contact/views.py
from django.shortcuts import render

# Create your views here.


def index(request):

    return render(request, 'contact/index.html')

DjangoTutorial/mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect

from django.urls import reverse

from .models import Question

from django.shortcuts import render, get_object_or_404

# Create your views here.


def contact(request):

    return render(request, 'polls/contact.html')


def index(request):

    latest_questions = Question.objects.order_by('-pub_date')[:5]

    context = {'latest_questions': latest_questions}

    return render(request, 'polls/index.html', context)


def detail(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):

    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except:
        return render(request, 'polls/detail.html', {'question': question, 'error_message': "Please select a choice."})
    else:
        selected_choice.num_of_votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=question_id,))

DjangoTutorial/mysite/contact/templates/contact/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>voteVotevote!</title>
</head>
<body>

<style>
.header {
    position: fixed;
    width: 100%;
    background-color: blue;
    color: white;
    text-align: center;
}
</style>

<div class="header">
    <p> <b>Welcome to my website! </b></p>
</div>
<br>
<br>
<br>
<br>
<h1> Contact us </h1>

<strong> Telephone: </strong>+1 22342234
<br>
<strong> Email: </strong>vote@vote.com

<hr>

</body>
</html>

DjangoTutorial/mysite/polls/templates/polls/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>voteVotevote!</title>
    <link rel="stylesheet" type="text/css" href = "{% static 'polls/style.css' %}">
</head>
<body>

<style>
.header {
    position: fixed;
    width: 100%;
    background-color: blue;
    color: white;
    text-align: center;
}
</style>

<div class="header">
    <p> <b>Welcome to my website! </b></p>
</div>
<br>
<br>
<br>
<br>
<strong><a href = {% url "polls:index" %}><b><strong>Home Page</strong></b></a></li>
<hr>

{% block main_content %}

{% endblock %}

{% include 'polls/footer.html' %}

</body>
</html>

DjangoTutorial/mysite/polls/templates/polls/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>voteVotevote!</title>
</head>
<body>

<style>
.header {
    position: fixed;
    width: 100%;
    background-color: blue;
    color: white;
    text-align: center;
}
</style>

<div class="header">
    <p> <b>Welcome to my website! </b></p>
</div>
<br>
<br>
<br>
<br>
<h1> Contact us </h1>

<strong> Telephone: </strong>+1 22342234
<br>
<strong> Email: </strong>vote@vote.com

<hr>

</body>
</html>

DjangoTutorial/mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1> {{question.question_text}} </h1>

{% if error_message %} <p> <strong> {{error_message}} </strong></p> {% endif %}

<form action = "{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>

        <label for="choice{{forloop.counter}}"> {{choice.choice_text}} </label> <br><br>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

{% endblock %}

DjangoTutorial/mysite/polls/templates/polls/footer.html
<style>
.footer {
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    background-color: blue;
    color: white;
    text-align: center;
}
</style>

<div class="footer">
    <ul><a href= {% url 'contact:index' %}><b>Contact Us</b></a></ul>
</div>

DjangoTutorial/mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block main_content %}

{% if latest_questions %}
    <ul>
        {% for question in latest_questions %}
            <li><a href = {% url "polls:detail" question.id %}><b>{{question.question_text}}</b></a></li>
        {% endfor %}
    </ul>
{% else %}
    <p> You don't have any questions. Please add one. </p>
{% endif %}

{% endblock %}

DjangoTutorial/mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1> {{question.question_text}} </h1>

<ul>

    {% for choice in question.choice_set.all %}
        <li> {{choice.choice_text}} -- {{choice.num_of_votes}} vote{{ choice.num_of_votes|pluralize}}</li>
    {% endfor %}

</ul>

<li><a href = {% url "polls:detail" question.id %}><b>Vote Again?</b></a></li>

{% endblock %}